//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOriginatorResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class GetOriginatorResponse : object
    {
        
        private int ErrorCodeField;
        
        private SmsProxy.ArrayOfString OriginatorListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SmsProxy.ArrayOfString OriginatorList
        {
            get
            {
                return this.OriginatorListField;
            }
            set
            {
                this.OriginatorListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", ItemName="Originator")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCreditResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class GetCreditResponse : object
    {
        
        private int ErrorCodeField;
        
        private System.Nullable<int> AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSmsResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class SendSmsResponse : object
    {
        
        private int ErrorCodeField;
        
        private string PacketIdField;
        
        private SmsProxy.ArrayOfLong MessageIdListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PacketId
        {
            get
            {
                return this.PacketIdField;
            }
            set
            {
                this.PacketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SmsProxy.ArrayOfLong MessageIdList
        {
            get
            {
                return this.MessageIdListField;
            }
            set
            {
                this.MessageIdListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", ItemName="MessageId")]
    public class ArrayOfLong : System.Collections.Generic.List<long>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetStatusResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class GetStatusResponse : object
    {
        
        private int ErrorCodeField;
        
        private SmsProxy.MessageStatus[] MessageStatusListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SmsProxy.MessageStatus[] MessageStatusList
        {
            get
            {
                return this.MessageStatusListField;
            }
            set
            {
                this.MessageStatusListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStatus", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class MessageStatus : object
    {
        
        private long MessageIdField;
        
        private long PacketIdField;
        
        private string ReceiverField;
        
        private byte MessageSizeField;
        
        private string PersonalParameterField;
        
        private int StatusField;
        
        private string DeliveryDateField;
        
        private string ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long PacketId
        {
            get
            {
                return this.PacketIdField;
            }
            set
            {
                this.PacketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public byte MessageSize
        {
            get
            {
                return this.MessageSizeField;
            }
            set
            {
                this.MessageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PersonalParameter
        {
            get
            {
                return this.PersonalParameterField;
            }
            set
            {
                this.PersonalParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DeliveryDate
        {
            get
            {
                return this.DeliveryDateField;
            }
            set
            {
                this.DeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmSmsResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class ConfirmSmsResponse : object
    {
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbortSmsResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class AbortSmsResponse : object
    {
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", ConfigurationName="SmsProxy.SmsProxySoap")]
    public interface SmsProxySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.asistiletisim.com.tr/SmsProxy/getOriginator", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsProxy.getOriginatorResponse1> getOriginatorAsync(SmsProxy.getOriginatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.asistiletisim.com.tr/SmsProxy/getCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsProxy.getCreditResponse1> getCreditAsync(SmsProxy.getCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.asistiletisim.com.tr/SmsProxy/sendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsProxy.sendSmsResponse1> sendSmsAsync(SmsProxy.sendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.asistiletisim.com.tr/SmsProxy/getStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsProxy.getStatusResponse1> getStatusAsync(SmsProxy.getStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.asistiletisim.com.tr/SmsProxy/confirmSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsProxy.confirmSmsResponse1> confirmSmsAsync(SmsProxy.confirmSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.asistiletisim.com.tr/SmsProxy/abortSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsProxy.abortSmsResponse1> abortSmsAsync(SmsProxy.abortSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOriginatorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOriginator", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.getOriginatorRequestBody Body;
        
        public getOriginatorRequest()
        {
        }
        
        public getOriginatorRequest(SmsProxy.getOriginatorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class getOriginatorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public getOriginatorRequestBody()
        {
        }
        
        public getOriginatorRequestBody(string requestXml)
        {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOriginatorResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOriginatorResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.getOriginatorResponse1Body Body;
        
        public getOriginatorResponse1()
        {
        }
        
        public getOriginatorResponse1(SmsProxy.getOriginatorResponse1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class getOriginatorResponse1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsProxy.GetOriginatorResponse getOriginatorResult;
        
        public getOriginatorResponse1Body()
        {
        }
        
        public getOriginatorResponse1Body(SmsProxy.GetOriginatorResponse getOriginatorResult)
        {
            this.getOriginatorResult = getOriginatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCredit", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.getCreditRequestBody Body;
        
        public getCreditRequest()
        {
        }
        
        public getCreditRequest(SmsProxy.getCreditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class getCreditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public getCreditRequestBody()
        {
        }
        
        public getCreditRequestBody(string requestXml)
        {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCreditResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.getCreditResponse1Body Body;
        
        public getCreditResponse1()
        {
        }
        
        public getCreditResponse1(SmsProxy.getCreditResponse1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class getCreditResponse1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsProxy.GetCreditResponse getCreditResult;
        
        public getCreditResponse1Body()
        {
        }
        
        public getCreditResponse1Body(SmsProxy.GetCreditResponse getCreditResult)
        {
            this.getCreditResult = getCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSms", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.sendSmsRequestBody Body;
        
        public sendSmsRequest()
        {
        }
        
        public sendSmsRequest(SmsProxy.sendSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class sendSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public sendSmsRequestBody()
        {
        }
        
        public sendSmsRequestBody(string requestXml)
        {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSmsResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.sendSmsResponse1Body Body;
        
        public sendSmsResponse1()
        {
        }
        
        public sendSmsResponse1(SmsProxy.sendSmsResponse1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class sendSmsResponse1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsProxy.SendSmsResponse sendSmsResult;
        
        public sendSmsResponse1Body()
        {
        }
        
        public sendSmsResponse1Body(SmsProxy.SendSmsResponse sendSmsResult)
        {
            this.sendSmsResult = sendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStatus", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.getStatusRequestBody Body;
        
        public getStatusRequest()
        {
        }
        
        public getStatusRequest(SmsProxy.getStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class getStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public getStatusRequestBody()
        {
        }
        
        public getStatusRequestBody(string requestXml)
        {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatusResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStatusResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.getStatusResponse1Body Body;
        
        public getStatusResponse1()
        {
        }
        
        public getStatusResponse1(SmsProxy.getStatusResponse1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class getStatusResponse1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsProxy.GetStatusResponse getStatusResult;
        
        public getStatusResponse1Body()
        {
        }
        
        public getStatusResponse1Body(SmsProxy.GetStatusResponse getStatusResult)
        {
            this.getStatusResult = getStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="confirmSms", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.confirmSmsRequestBody Body;
        
        public confirmSmsRequest()
        {
        }
        
        public confirmSmsRequest(SmsProxy.confirmSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class confirmSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public confirmSmsRequestBody()
        {
        }
        
        public confirmSmsRequestBody(string requestXml)
        {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmSmsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="confirmSmsResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.confirmSmsResponse1Body Body;
        
        public confirmSmsResponse1()
        {
        }
        
        public confirmSmsResponse1(SmsProxy.confirmSmsResponse1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class confirmSmsResponse1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsProxy.ConfirmSmsResponse confirmSmsResult;
        
        public confirmSmsResponse1Body()
        {
        }
        
        public confirmSmsResponse1Body(SmsProxy.ConfirmSmsResponse confirmSmsResult)
        {
            this.confirmSmsResult = confirmSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class abortSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="abortSms", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.abortSmsRequestBody Body;
        
        public abortSmsRequest()
        {
        }
        
        public abortSmsRequest(SmsProxy.abortSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class abortSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public abortSmsRequestBody()
        {
        }
        
        public abortSmsRequestBody(string requestXml)
        {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class abortSmsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="abortSmsResponse", Namespace="https://webservice.asistiletisim.com.tr/SmsProxy", Order=0)]
        public SmsProxy.abortSmsResponse1Body Body;
        
        public abortSmsResponse1()
        {
        }
        
        public abortSmsResponse1(SmsProxy.abortSmsResponse1Body Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.asistiletisim.com.tr/SmsProxy")]
    public partial class abortSmsResponse1Body
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsProxy.AbortSmsResponse abortSmsResult;
        
        public abortSmsResponse1Body()
        {
        }
        
        public abortSmsResponse1Body(SmsProxy.AbortSmsResponse abortSmsResult)
        {
            this.abortSmsResult = abortSmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SmsProxySoapChannel : SmsProxy.SmsProxySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SmsProxySoapClient : System.ServiceModel.ClientBase<SmsProxy.SmsProxySoap>, SmsProxy.SmsProxySoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SmsProxySoapClient() : 
                base(SmsProxySoapClient.GetDefaultBinding(), SmsProxySoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SmsProxySoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SmsProxySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SmsProxySoapClient.GetBindingForEndpoint(endpointConfiguration), SmsProxySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SmsProxySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SmsProxySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SmsProxySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SmsProxySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SmsProxySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SmsProxy.getOriginatorResponse1> getOriginatorAsync(SmsProxy.getOriginatorRequest request)
        {
            return base.Channel.getOriginatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsProxy.getCreditResponse1> getCreditAsync(SmsProxy.getCreditRequest request)
        {
            return base.Channel.getCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsProxy.sendSmsResponse1> sendSmsAsync(SmsProxy.sendSmsRequest request)
        {
            return base.Channel.sendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsProxy.getStatusResponse1> getStatusAsync(SmsProxy.getStatusRequest request)
        {
            return base.Channel.getStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsProxy.confirmSmsResponse1> confirmSmsAsync(SmsProxy.confirmSmsRequest request)
        {
            return base.Channel.confirmSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsProxy.abortSmsResponse1> abortSmsAsync(SmsProxy.abortSmsRequest request)
        {
            return base.Channel.abortSmsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SmsProxySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SmsProxySoap))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.asistiletisim.com.tr/SmsProxy.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SmsProxySoapClient.GetBindingForEndpoint(EndpointConfiguration.SmsProxySoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SmsProxySoapClient.GetEndpointAddress(EndpointConfiguration.SmsProxySoap);
        }
        
        public enum EndpointConfiguration
        {
            
            SmsProxySoap,
        }
    }
}
